---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: 包含多項新功能與增強功能。Cloud Volumes ONTAP 
---
= 更新功能Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
包含多項新功能與增強功能。Cloud Volumes ONTAP

最新版Cloud Manager也會提供其他功能與增強功能。請參閱 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Cloud Manager版本資訊"^] 以取得詳細資料。



== 9.6 P8（2020年6月2日）

9.6 P8 for Cloud Volumes ONTAP NetApp的修補程式版本現在可透過Cloud Manager 3.8及更新版本取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P8["檢視P8修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.6 P7（2020年4月8日）

適用於VMware的9.6 P7修補程式版本Cloud Volumes ONTAP 現已透過Cloud Manager 3.8及更新版本提供。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P7["檢視P7修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.6 P6（2020年3月6日）

9.6 P6的更新版本Cloud Volumes ONTAP 適用於整個過程、現在可透過Cloud Manager 3.8及更新版本取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P6["檢視在p6修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== AWS更新（2020年2月16日）

我們已推出新EC2執行個體的支援、以及支援的資料磁碟數量的變更。



=== 支援新執行個體

使用Premium或BYOL授權時、目前支援幾種新型EC2執行個體類型Cloud Volumes ONTAP 的功能。

* c5.9xlarge
* c5d.18xlarge、^1、2^
* m5d.8xlarge、^1、2^


^1^這些執行個體類型包括本機NVMe儲存設備、Cloud Volumes ONTAP 此儲存設備用作_Flash Cache。 https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["深入瞭解"^]。

9.6 P3及更新版本支援這些執行個體類型。

https://aws.amazon.com/ec2/instance-types/["深入瞭解這些EC2執行個體類型"^]。

link:reference-configs-aws.html["深入瞭解AWS支援的9.6組態"]。



=== 支援的資料磁碟

現在、對於c5、m5和R5執行個體、可減少一個資料磁碟。對於單一節點系統、支援22個資料磁碟。對於HA配對、每個節點支援19個資料磁碟。

link:reference-limits-aws.html["深入瞭解AWS的儲存限制"]。



== 支援Azure中的DS15_v2（2020年2月12日）

目前、無論是單一節點系統或HA配對、Azure中的DS15_v2虛擬機器類型都支援此功能。Cloud Volumes ONTAP

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["深入瞭解DSv2系列"^]。

link:reference-configs-azure.html["深入瞭解Azure支援的9.6組態"]。



== 9.6 P5（2019年12月26日）

9.6 FP5 for Cloud Volumes ONTAP NetApp的修補程式版本現已透過Cloud Manager推出。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P5["檢視在P5修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.6 P4（2019年11月14日）

9.6 P4 for Cloud Volumes ONTAP NetApp的修補程式版本現在可透過Cloud Manager取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P4["檢視P4修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.6 P3（2019年10月23日）

9.6 P3版的Cloud Volumes ONTAP 更新版for the NetApp現在可透過Cloud Manager取得。Cloud Manager會提示您將現有系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P3["檢視P3修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。

除了錯誤修復之外、此版本也能啟用下列功能：

* 支援AWS中的c5.18xlarge執行個體類型。
* Azure中單一節點系統的最大集合體大小增加：目前支援352TB原始容量。
+
單一節點系統的最大Aggregate大小先前為200 TB。





== Google Cloud Marketplace的隨用隨付訂閱（2019年10月6日）

您現在Cloud Volumes ONTAP 可以在Cloud Volumes ONTAP Google Cloud Platform Marketplace訂閱《關於解決方案的資訊》、一次購買即可獲得「解決方案的資訊」。

https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?q=NetApp&id=8108721b-10e5-48be-88ed-387031dae492["Google Cloud Platform Marketplace：Cloud Manager for Cloud Volumes ONTAP 架構"^]



== Google Cloud中的通用功能（2019年9月3日）Cloud Volumes ONTAP

現在、當您自帶授權（BYOL）時、Google Cloud Platform（Google Cloud）通常會提供此功能。Cloud Volumes ONTAP您也可以參加隨用隨付促銷活動。促銷活動提供無限數量系統的免費授權、將於2019年9月底到期。

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-getting-started-gcp.html["瞭解如何開始使用Google Cloud"^]
* link:reference-configs-gcp.html["檢視支援的組態"]




== 9.6 P2（2019年8月29日）

9.6 P2版的Cloud Volumes ONTAP 更新版適用於整個過程、現在可透過Cloud Manager取得。Cloud Manager會提示您將現有的9.5和9.6系統升級至此修補程式版本。 https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.6P2["檢視P2修補程式中修正的錯誤清單"^] （需要NetApp支援網站登入）。



== 9.6 GA（2019年7月15日）

目前已推出《一般供應（GA）Cloud Volumes ONTAP 》版本的《The General Availability》（更新版本）。GA版本包含錯誤修正。Cloud Manager會提示您將現有系統升級至此版本。


NOTE: 在Google Cloud Platform中、可將其保留在私有預覽中。Cloud Volumes ONTAP



== 9.6 RC1（2019年6月16日）

適用於AWS、Azure及Google Cloud Platform的RC9.6 RC1。Cloud Volumes ONTAP此版本包含下列功能。

* <<Google Cloud Volumes ONTAP Cloud Platform中的私有版功能預覽>>
* <<Azure中的HA配對資料分層>>
* <<支援FlexCache 支援功能>>
* <<其他ONTAP 功能變更>>




=== Google Cloud Volumes ONTAP Cloud Platform中的私有版功能預覽

Google Cloud Platform提供個人版Cloud Volumes ONTAP 的功能預覽。與其他雲端供應商類似、Cloud Volumes ONTAP 適用於Google Cloud Platform的解決方案可協助您降低成本、改善效能及提高可用度。

可在Google Cloud中以單一節點系統的形式取得、並支援資料分層至物件儲存設備。Cloud Volumes ONTAP

若要加入私人預覽、請傳送要求至ng-Cloud-Volume-ONTAP-preview@netapp.com。



=== Azure中的HA配對資料分層

Microsoft Cloud Volumes ONTAP Azure中的資料分層功能現在支援使用不含更新功能的成對功能。資料分層功能可將非作用中資料自動分層至低成本的Blob儲存設備。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html["瞭解如何在Cloud Manager中設定資料分層"^]。



=== 支援FlexCache 支援功能

流通量是儲存磁碟區、可快取來源（或來源）磁碟區的 NFS 讀取資料。 FlexCache後續讀取快取資料會加快該資料的存取速度。

您可以使用 FlexCache 功能區來加速資料存取、或卸載大量存取磁碟區的流量。由於資料無需存取來源磁碟區、因此能夠直接提供服務、因此在用戶端需要重複存取相同資料時、支援使用者更能提升效能。 FlexCache適用於讀取密集的系統工作負載的資料量。 FlexCache

Cloud Manager FlexCache 目前並未提供對各個版本的管理、但您可以使用 ONTAP CLI 或 ONTAP 功能完善的系統管理程式來建立及管理 FlexCache 各個版本：

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-fc-mgmt/home.html["《資料存取能力快速指南》的《支援資料量》（英文） FlexCache"^]
* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-07F4C213-076D-4FE8-A8E3-410F49498D49.html["在 FlexCache System Manager 中建立功能區"^]


從 3.7.2 版開始、 Cloud Manager 會為 FlexCache 所有的 Cloud Volumes ONTAP 全新推出的功能介紹系統產生一套功能不全的使用許可證。授權包含500 GiB使用限制。



=== 其他ONTAP 功能變更

NetApp 9.6包含其他非功能使用者可能感興趣的變更：ONTAP Cloud Volumes ONTAP

* SnapMirror複寫現在支援傳輸中通訊的TLS 1.2加密
* 資料分層FabricPool （物件）增強功能包括：
+
** 不需重新分層冷資料、即可支援Volume搬移
** SVM災難恢復支援




如需9.6版的詳細資訊、請參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["發行說明ONTAP"^]。



== 升級附註

* 必須從 Cloud Manager 完成升級。 Cloud Volumes ONTAP您不應 Cloud Volumes ONTAP 使用 System Manager 或 CLI 來升級功能。這樣做可能會影響系統穩定性。
* 您可以從Cloud Volumes ONTAP 9.5版升級至S69.6版。
* 單一節點系統的升級可讓系統離線長達25分鐘、在此期間I/O會中斷。
* 升級 HA 配對不中斷營運、而且 I/O 不中斷。在此不中斷營運的升級程序中、會同時升級每個節點、以繼續為用戶端提供 I/O 服務。

